### ISSUE TITLE
метод с маленькой буквы

### ISSUE THREAD

**Issue by tgurskaya96** [heycarl/BSUIR_PiHLL#1]
https://github.com/heycarl/BSUIR_PiHLL/blob/2b2882b3b71754d3d44949ad958ed397ca74a3db/src/main/java/grvt/cloud/epam_web/controllers/AlliveController.java#L9

**Comment by heycarl** [comment]
Исправлено в [8c8736e](https://github.com/heycarl/BSUIR_PiHLL/commit/8c8736ebbf01ef413cd4d5e39cef0ff3bf8e6795)
