### ISSUE TITLE
В названиях пакетов _ не используется

### ISSUE THREAD

**Issue by tgurskaya96** [heycarl/BSUIR_PiHLL#2]
https://github.com/heycarl/BSUIR_PiHLL/blob/2b2882b3b71754d3d44949ad958ed397ca74a3db/src/main/java/grvt/cloud/epam_web/perfomance_counter/CounterLogic.java#L1

**Comment by heycarl** [comment]
Судя по источникам ниже, общепринятой конвенции именования пакетов не существует  
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
https://stackoverflow.com/questions/3179216/what-is-the-convention-for-word-separator-in-java-package-names
