### ISSUE TITLE
1.Метод с маленькой буквы, 2. код метода выглядит как конструктор

### ISSUE THREAD

**Issue by tgurskaya96** [heycarl/BSUIR_PiHLL#4]
https://github.com/heycarl/BSUIR_PiHLL/blob/2b2882b3b71754d3d44949ad958ed397ca74a3db/src/main/java/grvt/cloud/epam_web/models/Triangle.java#L45

**Comment by heycarl** [comment]
Название метода поправил, по содержимому - это сеттер на сразу 3 стороны треугольника, который остался с этапа создания тестов. Там создается один объект треугольника, стороны которого меняются с помощью этого метода, а затем проверяются свойства. В теории можно исправить перезаписю объекта новым, созданным с помощью конструктора, но не уверен, что это правильное решение проблемы.
