### ISSUE TITLE
Зачем эта переменная и почему туда передаётся контроллер?

### ISSUE THREAD

**Issue by tgurskaya96** [heycarl/BSUIR_PiHLL#7]
https://github.com/heycarl/BSUIR_PiHLL/blob/2b2882b3b71754d3d44949ad958ed397ca74a3db/src/main/java/grvt/cloud/epam_web/perfomance_counter/Counter.java#L8

**Comment by heycarl** [comment]
Исправлено в [e1e62ce](https://github.com/heycarl/BSUIR_PiHLL/commit/e1e62ce623dda928e95462a46656869e95870604)
