### ISSUE TITLE
Вынести валидацию в отдельный класс

### ISSUE THREAD

**Issue by tgurskaya96** [heycarl/BSUIR_PiHLL#8]
https://github.com/heycarl/BSUIR_PiHLL/blob/2b2882b3b71754d3d44949ad958ed397ca74a3db/src/main/java/grvt/cloud/epam_web/models/Triangle.java#L50

**Comment by heycarl** [comment]
Стоит вынести **только** статический метод, как метод, в целом валидирующий сторону?
