### ISSUE TITLE
Где используется логгер в этом классе?

### ISSUE THREAD

**Issue by tgurskaya96** [heycarl/BSUIR_PiHLL#9]
Исправлено в [e1e62ce](https://github.com/heycarl/BSUIR_PiHLL/commit/e1e62ce623dda928e95462a46656869e95870604)

_Originally posted by @heycarl in https://github.com/heycarl/BSUIR_PiHLL/issues/7#issuecomment-1483349731_

**Comment by heycarl** [comment]
Осталось от тестирования счетчика. Исправил в [9efd12d](https://github.com/heycarl/BSUIR_PiHLL/commit/9efd12d68e03fdfae6ba55dd05fd1a45c8dbc5df)
